apiVersion: v1
kind: Service
metadata:
  name: ${{values.application_id}}
  namespace: suxess-it-${{values.environments}}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ${{values.application_id}}
  type: ClusterIP