#{% for environment in values.environments.split(",") %}
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{values.application_id}}
  description: ${{values.description}}
  labels:
    environments: ${{environment}}
spec:
  owner: ${{values.owner}}
#{% endfor %}