apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "${{values.application_id}}"
  description: "${{values.application_id}}"
  tags:
    - sx
    - template
  links:
    - url: https://graf-sx-grafana.apps.cluster1.mcp.pitagora.at
      title: SRE Metrics (production)
      icon: web
  annotations:
    github.com/project-slug: phac008/${{values.application_id}}
    'backstage.io/kubernetes-id': ${{values.application_id}}
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=${{values.application_id}}'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "guests"
  system: system:${{values.application_id}}