apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: sx-application-template
  title: sX Application Template
  description: Run Demo Application in ArgoCD namespace
  tags:
    - application
spec:
  owner: phac@suxess-it.com
  type: system
  
  parameters:
    - title: Provide information on this application
      required:
        - application_id
        - owner
        - environments
        - description
        - dockerimage
      properties:
        application_id:
          title: Name
          type: string
          description: Unique name of this application
        description:
          title: Description
          type: string
          description: Help others understand what this application is for.
        owner:
          title: Owner
          type: string
          description: Owner of this applications
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - Group
        dockerimage:
          title: Dockerimage Location
          type: string                      
        environments:
          title: Environments
          type: string
          description: Environments needed by this application
          items:
            type: array
            enum: 
              - prod
              - dev
              - qa
              - prod,dev,qa
          uniqueItems: true
          ui:widget: checkboxes
        replicas:
          title: Number of replicas for Pods
          type: string
          

  steps:
    - id: template-namespaces 
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender: []
        values:
          application_id: ${{ parameters.application_id }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          environments: ${{ parameters.environments }}

    - id: pull-request
      name: make a pr with the new namespaces
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=approved-namespaces&owner=phac008
        branchName: ${{ parameters.application_id }}
        title: argoapps and system config for ${{ parameters.application_id }}
        description: argoapps and system config for ${{ parameters.application_id }}
        

    - id: template-gitops
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./app-gitops
        copyWithoutRender: []
        values: {}
        targetPath: ./app-gitops

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.application_id }}
        repoUrl: github.com?repo=${{ parameters.application_id }}-gitops&owner=phac008
        repoVisibility: public
        sourcePath: ./app-gitops
        deleteBranchOnMerge: true
        #access: phac008/${{ parameters.owner }}
        protectDefaultBranch: false
